### PR TITLE
focus recording purchase&submit integration

### PR DESCRIPTION
**Pull request by truomegacoder**

### CODE REVIEW

**Comment by xzistance** [comment]
Good start here! Need to address a handful of things. I'm assuming this wasn't completely finalized, so apologies if I'm delving into logic that we are still hashing out.

1. Are we sure we want to piggyback focus videos onto the current Videos synapse request? From a scoring perspective, maybe that is what is needed in order to be able to apply the 8:2 yt to focus ratio? I'm honestly not sure because I'm still learning how scoring fully works.

Current miners already have a fairly time-intensive task to retrieve the youtube videos and generate their metadata. So, the timeout could play a factor. Even more so depending on #2 below.

2. There is no handling/generation of metadata, including embeddings for focus vids. Typically, miners take youtube videos and then process them, creating the metadata (https://github.com/omegalabsinc/omegalabs-bittensor-subnet/blob/196ab64c2062deb12b51d4e07c71753cfc7a7b34/omega/protocol.py#L25-L36). I don't see that happening here for focus videos.

I would think we need those generated somewhere in preparation for uploading to pinecone and huggingface.

Do we already have all that metadata defined from the focus app and stored in a db?
Does it make sense for a miner to take on the responsibility of generating the metadata? embeddings and proper description.

3. Do we need to do any similarity checks for focus app videos? The current flow has the scoring being handled on the Focus App side and just accepted as-is on the Bittensor validator side. Do we need to do some kind of scoring check on the validator side to make sure the focus-generated score is good?

4. This flow is only using the `/api/validate` endpoint, which is the non-decentralized (old) method that most validators no longer use.

In fact, I would vote to fully deprecate that endpoint (@salmanshah1d -- thoughts?)

If we keep this flow as-is, logic is going to have to be built into the `handle_checks_and_rewards` flow (https://github.com/omegalabsinc/omegalabs-bittensor-subnet/blob/196ab64c2062deb12b51d4e07c71753cfc7a7b34/neurons/validator.py#L226).

5. How are we uploading the focus app videos and their metadata to the pinecone index and huggingface? This goes with #2.

Along with #3, do we blindly upload the focus video metadata to our index or do we apply `is_too_similar` logic? There is the potential of mis-calculated videos via the focus app that become too similar once they get to the validators.

i.e. Focus app user records task XYZ. Focus app calculates it to be worth 0.5.
Time goes by, other focus app videos are processed and put into the index.
Miner eventually purchases focus app video XYZ and gets it processed. There are now overlapping embeddings and the score is either reduced or the video embeddings are now `is_too_similar`. 

How would we handle that? 

6. How are we indicating that a purchased miner video has been consumed? I would assume this has to happen immediately following when a validator scores it to the chain.

7. Is the current solution too centralized? Meaning, we're still communicating directly with a database that is behind closed doors and not public. I think Salman mentioned wanting to post metadata for each focus app video to the chain and then have validators detect that and process them. Would require reworking of what is happening here, of course.

**Comment by truomegacoder** [comment]
thanks for your review, @xzistance.

for 2, I will add functionality to generate embeddings for uploading focus video to pinecone. that's really needed for deduplication.
for 3&4, I will move the focus video validation from `/api/validate` endpoint to validator code, so validators can perform validation on their own.
for 5, So it means we need to implement is_too_smilar in the focus app?
for 6, I agree with your idea and it is currently implemented in the validator api. will mark as Consumed for the purchased focus videos in DB after consumed.

**Comment by xzistance** [comment]
Sweet. Will respond inline:

_for 2, I will add functionality to generate embeddings for uploading focus video to pinecone. that's really needed for deduplication._
Yeah, based on our discussion this morning, this would be done by the validator in the process of scoring it. 

_for 3&4, I will move the focus video validation from /api/validate endpoint to validator code, so validators can perform validation on their own._
Perfect, thank you.

_for 5, So it means we need to implement is_too_smilar in the focus app?_
I think it makes sense, yeah. If we are scoring these the exact same way we are scoring Youtube videos (aside from the weighting ratio), then yeah. You'll want to look into the logic in `handle_checks_and_rewards` for how to replicate that on the focus app side.

_for 6, I agree with your idea and it is currently implemented in the validator api. will mark as Consumed for the purchased focus videos in DB after consumed._
Gotcha, I may have missed that. I think that will have to happen on the validator side now right after they set weights and it's successful. If we put it on the vali API side, we risk a failure on both the vali API and the focus app API. We will probably want to write to the block chain similar to how we will do it when a miner officially purchases a focus video -- just another public ledger saying the video has been consumed and is no longer available for consumption.

**Review by xzistance — APPROVED** [review]
Approved with the adjustments made.

**Pull request merged**
